# GENERATED by tools/gen_dhcpv4_wire.py from
# src/sce_integration/dhcpv4_wire.def — DO NOT EDIT.
# Regenerate: python3 tools/gen_dhcpv4_wire.py
#
# Python mirror of the DHCPv4 BOOTP fixed-header decode. The C++
# authoritative decoder (src/sce_integration/dhcpv4_wire.h) #includes
# the same .def directly, so this file and the harness share one
# layout. Imported by site/scripts/decode_pcap.py. The options TLV
# chain has no fixed offsets and is walked by the caller, outside this
# mirror. See docs/tech-debt.md TD-02.


def _read(buf, off, size):
    """Big-endian field read; twin of ::tc8::wire::readBe (C++)."""
    value = 0
    for i in range(size):
        value = (value << 8) | buf[off + i]
    return value


def _ipv4(buf, off):
    return ".".join(str(b) for b in buf[off:off + 4])


kMagicCookieOff = 236
kMagicCookie = 0x63825363
kOptionsOff = 240


def decode_bootp_fixed_header(buf):
    """RFC 951 / RFC 2131 BOOTP fixed header (op..chaddr).
    Caller guarantees at least kOptionsOff bytes."""
    return {
        "op": _read(buf, 0, 1),
        "htype": _read(buf, 1, 1),
        "hlen": _read(buf, 2, 1),
        "hops": _read(buf, 3, 1),
        "xid": _read(buf, 4, 4),
        "secs": _read(buf, 8, 2),
        "flags": _read(buf, 10, 2),
        "ciaddr": _ipv4(buf, 12),
        "yiaddr": _ipv4(buf, 16),
        "siaddr": _ipv4(buf, 20),
        "giaddr": _ipv4(buf, 24),
        "chaddr": bytes(buf[28:28 + 16]),
    }


def magic_cookie_valid(buf):
    """True iff the 4 bytes at kMagicCookieOff equal the cookie."""
    return _read(buf, kMagicCookieOff, 4) == kMagicCookie
