# GENERATED by tools/gen_someip_sd_wire.py from
# src/sce_integration/someip_sd_wire.def — DO NOT EDIT.
# Regenerate: python3 tools/gen_someip_sd_wire.py
#
# Python mirror of the SOME/IP-SD wire decode. The C++ authoritative
# decoder (src/sce_integration/someip_captured.h) #includes the same
# .def directly, so this file and the harness share one layout. Imported
# by site/scripts/decode_pcap.py. See docs/tech-debt.md TD-01.


def _read(buf, off, size, shift, mask):
    """Big-endian field read; twin of ::tc8::wire::readBe (C++)."""
    value = 0
    for i in range(size):
        value = (value << 8) | buf[off + i]
    return (value >> shift) & mask


def _ipv4(buf, off):
    return ".".join(str(b) for b in buf[off:off + 4])


SD_ENTRY_TAIL_GROUP = {0x00: 'service', 0x01: 'service', 0x06: 'eventgroup', 0x07: 'eventgroup'}
SD_IPV4_OPTION_TYPES = (0x04, 0x14, 0x24)


def decode_sd_header(buf):
    """SD header flags + 24-bit reserved (caller guarantees >= 4 bytes)."""
    return {
        "sd_flags": _read(buf, 0, 1, 0, 0xff),
        "sd_reserved": _read(buf, 1, 3, 0, 0xffffff),
    }


def decode_sd_entries_len(buf):
    """LengthOfEntriesArray (caller guarantees >= 8 bytes)."""
    return _read(buf, 4, 4, 0, 0xffffffff)


def decode_sd_entry(buf, off, e_type):
    """16-byte SD entry. Common fields always; the tail group
    matching e_type only (the C++ struct carries both tails, but a
    dict need only hold the meaningful one)."""
    e = {}
    e["type"] = _read(buf, off, 1, 0, 0xff)
    e["index_first"] = _read(buf, off + 1, 1, 0, 0xff)
    e["index_second"] = _read(buf, off + 2, 1, 0, 0xff)
    e["num_opt1"] = _read(buf, off + 3, 1, 4, 0x0f)
    e["num_opt2"] = _read(buf, off + 3, 1, 0, 0x0f)
    e["service_id"] = _read(buf, off + 4, 2, 0, 0xffff)
    e["instance_id"] = _read(buf, off + 6, 2, 0, 0xffff)
    e["major_version"] = _read(buf, off + 8, 1, 0, 0xff)
    e["ttl"] = _read(buf, off + 9, 3, 0, 0xffffff)
    group = SD_ENTRY_TAIL_GROUP.get(e_type)
    if group == "service":
        e["minor_version"] = _read(buf, off + 12, 4, 0, 0xffffffff)
    elif group == "eventgroup":
        e["entry_reserved"] = _read(buf, off + 12, 2, 4, 0xfff)
        e["counter"] = _read(buf, off + 12, 2, 0, 0x0f)
        e["eventgroup_id"] = _read(buf, off + 14, 2, 0, 0xffff)
    return e


def decode_sd_option_ipv4(buf, off):
    """IPv4 endpoint/multicast/sd-endpoint option tail."""
    return {
        "reserved1": _read(buf, off + 3, 1, 0, 0xff),
        "ipv4": _ipv4(buf, off + 4),
        "reserved2": _read(buf, off + 8, 1, 0, 0xff),
        "l4_proto": _read(buf, off + 9, 1, 0, 0xff),
        "port": _read(buf, off + 10, 2, 0, 0xffff),
    }
