// GENERATED by tools/gen_expect_surface.py from
// tools/expect_surface.def — DO NOT EDIT.
// Regenerate: python3 tools/gen_expect_surface.py
//
// include!-d into dispatch.rs (uses its `ex` helper, the `wire` module, and
// `Config`). The base --expect identity surface, single-sourced with bash's
// tc8_expect_<bucket> functions so the two drivers cannot drift (TD-12). The
// --topology-conf extra_expect fold is spliced by expect_args BETWEEN these
// two appenders; the runtime DUT-MAC rows are filtered from the parity dump
// via RUNTIME_MAC_KEYS.

fn append_someip_identity(e: &mut Vec<String>, cfg: &Config) {
    let id = &cfg.identity;
    let t = &cfg.sd_timing;
    ex(e, "service_id", &id.service_id);
    ex(e, "instance_id", &id.instance_id);
    ex(e, "major_version", wire::SD_MAJOR_VERSION);
    ex(e, "ttl", &id.ttl);
    ex(e, "minor_version", wire::SD_MINOR_VERSION);
    ex(e, "eventgroup_id", wire::SD_DEFAULT_EVENTGROUP);
    ex(e, "dut_iface_ip", &cfg.dut_ip4);
    // Tester's own IPv4 for the someip group (bare key, like dut_iface_ip). Lets a
    // destination / Nack-target verdict compare a captured dst against the tester
    // endpoint instead of the unset-0 default; no in-tree case reads it yet.
    ex(e, "tester_ipv4", &cfg.tester_ip4);
    ex(e, "udp_port", &id.udp_port);
    ex(e, "tcp_port", &id.tcp_port);
    // SD_BEHAVIOR cases compare the DUT's multicast OfferService against the SD
    // multicast group (vsomeip service-discovery.multicast). Spec-section citations
    // live in the hand-edited drivers, not this generated surface (mnemosyne bindings).
    ex(e, "sd_multicast_ip", &id.sd_multicast_ip);
    // OPTIONS cases verify the IPv4 Multicast Option fields in the
    // SubscribeEventgroupAck for the multicast eventgroup (vsomeip eventgroup block).
    ex(e, "mcast_ipv4", &id.mcast_ipv4);
    ex(e, "mcast_port", &id.mcast_port);
    // SD start-up timing (vsomeip service-discovery): the AUTOSAR SD Initial-Wait /
    // Repetition / cyclic-Offer phase checks compare their captured windows against
    // these; inert for every other case (the harness reads only what it references).
    ex(e, "sd_initial_delay_min_ms", &t.sd_initial_delay_min_ms);
    ex(e, "sd_initial_delay_max_ms", &t.sd_initial_delay_max_ms);
    ex(e, "sd_repetition_base_delay_ms", &t.sd_repetition_base_delay_ms);
    ex(e, "sd_repetitions_max", &t.sd_repetitions_max);
    ex(e, "sd_cyclic_offer_delay_ms", &t.sd_cyclic_offer_delay_ms);
}

fn append_l2l3_identity(e: &mut Vec<String>, cfg: &Config, dut_mac: &str) {
    ex(e, "arp.tester_ip", &cfg.tester_ip4);
    ex(e, "arp.dut_iface_ip", &cfg.dut_ip4);
    ex(e, "dut.ip", &cfg.dut_ip4);
    // Injected tester sender MAC — ARP_03/05 filter DUT-originated ARP Requests by
    // this sender_hw. wire.def ARP_TESTER_MAC == arp_builder.h kTesterInjectedMac.
    ex(e, "arp.tester_mac", wire::ARP_TESTER_MAC);
    // Second tester MAC — Phase 3b Group C cache-merge cases (ARP_32..35).
    ex(e, "arp.tester_mac2", wire::ARP_TESTER_MAC2);
    // Third tester MAC — Phase 3c Group D Response-learning case (ARP_40).
    ex(e, "arp.tester_mac3", wire::ARP_TESTER_MAC3);
    ex(e, "arp.dut_iface_mac", dut_mac);
    ex(e, "dut.mac", dut_mac);
    ex(e, "dhcpv4.dut_iface_mac", dut_mac);
    ex(e, "icmpv4.tester_ip", &cfg.tester_ip4);
    ex(e, "icmpv4.dut_iface_ip", &cfg.dut_ip4);
    ex(e, "icmpv4.echo_id", wire::ICMP_ECHO_ID);
    ex(e, "icmpv4.echo_seq", wire::ICMP_ECHO_SEQ);
    ex(e, "ipv4.tester_ip", &cfg.tester_ip4);
    ex(e, "ipv4.dut_iface_ip", &cfg.dut_ip4);
    // Netns alias IPs (setup-netns.sh) for the UDP_USER_INTERFACE caller-specified
    // IP axis. External topologies whose DUT carries different aliases override via
    // TC8_TOPOLOGY_{DUT,TESTER}_ALIAS_IP (bash side only).
    ex(e, "ipv4.dut_alias_ip", wire::DUT_ALIAS_IP);
    ex(e, "ipv4.tester_alias_ip", wire::TESTER_ALIAS_IP);
}

/// The per-worker DUT-MAC `--expect` keys (kernel-assigned veth MAC,
/// different per run and per driver) — filtered from the static
/// `--print-expect` parity dump by `print_static_identity`.
const RUNTIME_MAC_KEYS: [&str; 3] = ["arp.dut_iface_mac", "dut.mac", "dhcpv4.dut_iface_mac"];
