// GENERATED by tools/gen_verdict_taxonomy.py from
// src/sce_integration/verdict_taxonomy.def — DO NOT EDIT.
// Regenerate: python3 tools/gen_verdict_taxonomy.py
//
// include!-d as the `taxonomy` module and consumed by dispatch.rs::classify
// so the orchestrator derives the verdict wire-names from the same .def as
// the C++/bash/Python consumers. `skip` is a smoke-runner concept
// (capability / topology) layered on the non-conclusion disposition, not a
// DUT verdict class, so it is not generated here.

/// Wire-name of the success class (gate-green, exit 0).
pub const SUCCESS: &str = "pass";

/// Wire-name of the gate-red failure class (exit 1).
pub const FAIL: &str = "fail";

/// Non-conclusion class wire-names (exit code not 0 or 1): routed to
/// a non-gating skip but counted against the non-conclusion ceiling.
pub const NONCONCLUSION: &[&str] = &["inconclusive", "error"];
