// GENERATED by tools/gen_wire_manifest.py from
// tools/wire.def — DO NOT EDIT.
// Regenerate: python3 tools/gen_wire_manifest.py
//
// include!-d as the `wire` module (main.rs). Single home for the wire/
// fixture constants shared across the C++ stimulus builders, this crate,
// and the bash smoke-test profiles. Each constant names its external SSOT
// in wire.def, where the `cpp=` ones are cross-checked against the C++
// headers. A drift here silently turns a positive test into a false pass.

/// `kTesterInjectedMac` — the sender MAC the harness injects in ARP stimulus, and
/// the lladdr the DHCPv4 CM_05/_06 synthetic-gateway pin binds to. Locally-
/// administered (`02:` prefix) so it cannot collide with a real OUI.
pub const ARP_TESTER_MAC: &str = "02:00:00:00:00:A1";

/// `kTesterInjectedMac2` — Group C cache-merge cases (ARP_32..35).
pub const ARP_TESTER_MAC2: &str = "02:00:00:00:00:A2";

/// `kTesterInjectedMac3` — Group D Response-learning case ARP_40.
pub const ARP_TESTER_MAC3: &str = "02:00:00:00:00:A3";

/// `kIcmpEchoId`.
pub const ICMP_ECHO_ID: &str = "0x1234";

/// `kIcmpEchoSeq`.
pub const ICMP_ECHO_SEQ: &str = "0x5678";

/// `kDutAliasIp4Be` — DUT-side source-IP alias (UDP_USER_INTERFACE_07).
pub const DUT_ALIAS_IP: &str = "172.16.0.5";

/// `kTesterAliasIp4Be` — tester-side destination-IP alias (UDP_USER_INTERFACE_08).
pub const TESTER_ALIAS_IP: &str = "172.16.0.4";

/// `kUdpHost2IpBe` — the UDP_FIELDS_04/_05 "second host on the link" address.
/// single-pc bring-up pins `<HOST2_IP, tester_mac>` NUD_PERMANENT on the DUT side
/// so the DUT's egress ARP for it resolves without a real third node; the lwIP tap
/// fixture answers ARP for it from the tap (/32). One value, two consumers.
pub const HOST2_IP: &str = "172.16.0.3";

/// `kDefaultServerIdBe` — the Option-3 router the DHCPv4 CM_05/_06 conditioning pins.
pub const DHCPV4_SERVER1_IP4: &str = "172.16.0.10";

/// SD major version — SSOT: `dut/ets/ets.fidl`.
pub const SD_MAJOR_VERSION: &str = "1";

/// SD minor version — same SSOT.
pub const SD_MINOR_VERSION: &str = "0";

/// The UNCONFIGURED subscribe target (NOT a deployed eventgroup) several
/// SOMEIPSRV/ETS cases Nack-echo. Do NOT "correct" to a deployed eventgroup —
/// that breaks the Nack-echo baseline.
pub const SD_DEFAULT_EVENTGROUP: &str = "0x0001";

/// SOME/IP-SD port — SSOT `tc8::dut::kSdPort` (include/tc8/dut_config.h). The
/// registered SD port both the DUT and the tester stimulus bind to. Topology
/// overlays read $TC8_WIRE_SD_PORT for the SD destination port instead of
/// re-hardcoding 30490. Emitted decimal so bash/profiles use it as a port.
pub const SD_PORT: &str = "30490";

/// Tester-side primary IP (single-pc tester veth + lwIP tap host side).
pub const TESTER_IP: &str = "172.16.0.1";

/// DUT-side primary IP (single-pc DUT veth + lwIP DUT netif). The local DUT's
/// vsomeip.json `unicast` MUST equal this — vsomeip binds/advertises that
/// address, so a drift makes the DUT serve on an IP its netns does not own. The
/// json= glob pins this home across the base config AND every variant
/// (vsomeip-multi-*.json), which all share the netns IP (the netns IP is authority).
pub const DUT_IP: &str = "172.16.0.2";

/// DUT-side /24 netmask (lwIP netif; single-pc derives it from the CIDR). The
/// local DUT's vsomeip.json `netmask` mirrors it across base + variants; pinned here.
pub const DUT_MASK: &str = "255.255.255.0";

/// Topology-2 second veth pair (TIface-1) tester IP — the second broadcast
/// domain (172.17.0.0/24) for the dual-interface DHCP client usage case.
/// Consumed by setup-netns.sh (SECOND_VETH) and the Rust orchestrator's netns-pair
/// transport (secondary veth for USAGE_01, dut/env/orchestrator/src/topology/netns_pair.rs).
pub const TESTER_IP_2: &str = "172.17.0.1";

/// Topology-2 second veth pair (DIface-1) DUT IP.
pub const DUT_IP_2: &str = "172.17.0.2";

/// Host tap device the lwIP DUT attaches to.
pub const TAP: &str = "tc8lwip0";

/// Per-run scratch dir (DUT log + working files); host-global, flock-guarded.
pub const FIX_DIR: &str = "/tmp/tc8-lwipfix";

/// Where the last run's DUT log is preserved on teardown for postmortems.
pub const LAST_DUT_LOG: &str = "/tmp/tc8-lwipfix-last-dut.log";

/// flock file enforcing single-instance use of the host-global tap/scratch.
pub const LOCK_FILE: &str = "/var/lock/tc8-lwip-fixture.lock";

/// UT 0x17 ARP-cache conditioning window (virtual seconds). MUST track the lwIP
/// compile-time `ARP_MAXAGE` (default 300; dut/lwip_dut/lwipopts.h leaves it at
/// the default): the ARP_48/49 trait stimulus ages the table by exactly this to
/// cross the stack's `age >= ARP_MAXAGE` free condition.
pub const ARP_CACHE_TIMEOUT_S: &str = "300";

/// Harness watchdog backstop (seconds). The per-case SoT is the SCXML deadline +
/// stimulus budget; this is the global last-resort kill so a hung case cannot
/// stall the suite. Bash `HARNESS_BACKSTOP_SEC`, Rust `Config::backstop_sec`.
pub const BACKSTOP_SEC: u32 = 240;
