# GENERATED by tools/gen_expect_surface.py from
# tools/expect_surface.def — DO NOT EDIT.
# Regenerate: python3 tools/gen_expect_surface.py
#
# Sourced by smoke-test.sh. Each function assigns/prints the base --expect
# identity surface for its bucket, reading the caller's resolved source vars
# (DUT_ID / TESTER_IP4 / DUT_IP4 / TC8_WIRE_* via dynamic scope). The runtime
# DUT-MAC bucket takes the per-worker MAC as $1 and prints its lines for
# readarray (no shared global, so parallel workers cannot race).

tc8_expect_someip() {
    TC8_DUT_EXPECT=(
        --expect "service_id=${DUT_ID[service_id]}"
        --expect "instance_id=${DUT_ID[instance_id]}"
        --expect "major_version=${TC8_WIRE_SD_MAJOR_VERSION}"
        --expect "ttl=${DUT_ID[ttl]}"
        --expect "minor_version=${TC8_WIRE_SD_MINOR_VERSION}"
        --expect "eventgroup_id=${TC8_WIRE_SD_DEFAULT_EVENTGROUP}"
        --expect "dut_iface_ip=${DUT_IP4}"
        # Tester's own IPv4 for the someip group (bare key, like dut_iface_ip). Lets a
        # destination / Nack-target verdict compare a captured dst against the tester
        # endpoint instead of the unset-0 default; no in-tree case reads it yet.
        --expect "tester_ipv4=${TESTER_IP4}"
        --expect "udp_port=${DUT_ID[udp_port]}"
        --expect "tcp_port=${DUT_ID[tcp_port]}"
        # SD_BEHAVIOR cases compare the DUT's multicast OfferService against the SD
        # multicast group (vsomeip service-discovery.multicast). Spec-section citations
        # live in the hand-edited drivers, not this generated surface (mnemosyne bindings).
        --expect "sd_multicast_ip=${DUT_ID[sd_multicast_ip]}"
        # OPTIONS cases verify the IPv4 Multicast Option fields in the
        # SubscribeEventgroupAck for the multicast eventgroup (vsomeip eventgroup block).
        --expect "mcast_ipv4=${DUT_ID[mcast_ipv4]}"
        --expect "mcast_port=${DUT_ID[mcast_port]}"
        # SD start-up timing (vsomeip service-discovery): the AUTOSAR SD Initial-Wait /
        # Repetition / cyclic-Offer phase checks compare their captured windows against
        # these; inert for every other case (the harness reads only what it references).
        --expect "sd_initial_delay_min_ms=${DUT_ID[sd_initial_delay_min_ms]}"
        --expect "sd_initial_delay_max_ms=${DUT_ID[sd_initial_delay_max_ms]}"
        --expect "sd_repetition_base_delay_ms=${DUT_ID[sd_repetition_base_delay_ms]}"
        --expect "sd_repetitions_max=${DUT_ID[sd_repetitions_max]}"
        --expect "sd_cyclic_offer_delay_ms=${DUT_ID[sd_cyclic_offer_delay_ms]}"
    )
}

tc8_expect_arp() {
    ARP_DUT_EXPECT_STATIC=(
        --expect "arp.tester_ip=${TESTER_IP4}"
        --expect "arp.dut_iface_ip=${DUT_IP4}"
        --expect "dut.ip=${DUT_IP4}"
        # Injected tester sender MAC — ARP_03/05 filter DUT-originated ARP Requests by
        # this sender_hw. wire.def ARP_TESTER_MAC == arp_builder.h kTesterInjectedMac.
        --expect "arp.tester_mac=${TC8_WIRE_ARP_TESTER_MAC}"
        # Second tester MAC — Phase 3b Group C cache-merge cases (ARP_32..35).
        --expect "arp.tester_mac2=${TC8_WIRE_ARP_TESTER_MAC2}"
        # Third tester MAC — Phase 3c Group D Response-learning case (ARP_40).
        --expect "arp.tester_mac3=${TC8_WIRE_ARP_TESTER_MAC3}"
    )
}

tc8_expect_mac() {
    local dut_mac=$1
    printf '%s\n' \
        --expect "arp.dut_iface_mac=$dut_mac" \
        --expect "dut.mac=$dut_mac" \
        --expect "dhcpv4.dut_iface_mac=$dut_mac"
}

tc8_expect_icmpv4() {
    ICMPV4_DUT_EXPECT_STATIC=(
        --expect "icmpv4.tester_ip=${TESTER_IP4}"
        --expect "icmpv4.dut_iface_ip=${DUT_IP4}"
        --expect "icmpv4.echo_id=${TC8_WIRE_ICMP_ECHO_ID}"
        --expect "icmpv4.echo_seq=${TC8_WIRE_ICMP_ECHO_SEQ}"
    )
}

tc8_expect_ipv4() {
    IPV4_DUT_EXPECT_STATIC=(
        --expect "ipv4.tester_ip=${TESTER_IP4}"
        --expect "ipv4.dut_iface_ip=${DUT_IP4}"
        # Netns alias IPs (setup-netns.sh) for the UDP_USER_INTERFACE caller-specified
        # IP axis. External topologies whose DUT carries different aliases override via
        # TC8_TOPOLOGY_{DUT,TESTER}_ALIAS_IP (bash side only).
        --expect "ipv4.dut_alias_ip=${TC8_TOPOLOGY_DUT_ALIAS_IP:-$TC8_WIRE_DUT_ALIAS_IP}"
        --expect "ipv4.tester_alias_ip=${TC8_TOPOLOGY_TESTER_ALIAS_IP:-$TC8_WIRE_TESTER_ALIAS_IP}"
    )
}
