# GENERATED by tools/gen_verdict_taxonomy.py from
# src/sce_integration/verdict_taxonomy.def — DO NOT EDIT.
# Regenerate: python3 tools/gen_verdict_taxonomy.py
#
# Sourced by smoke-test.sh. `skip` is a smoke-runner concept (capability /
# topology) layered onto the non-conclusion disposition, not a DUT verdict.
TC8_VERDICT_SUCCESS="pass"
TC8_VERDICT_NONCONCLUSION_RE="inconclusive|error"
