#!/usr/bin/env python3
"""Generate the Python (audit) + Bash (smoke gate) + doc mirrors of the verdict
taxonomy from the single source src/sce_integration/verdict_taxonomy.def.

The .def is also #included directly by verdict.h (C++), so all four consumers
derive from one place. Run with no args to (re)write the generated files;
run with --check to verify they are up to date (CI / pre-commit freshness gate).

Outputs:
  tools/verdict_taxonomy_gen.py                    imported by verdict_drift_audit.py
  dut/env/verdict_taxonomy.gen.sh                  sourced by smoke-test.sh
  dut/env/orchestrator/src/verdict_taxonomy.gen.rs include!-d by the orchestrator
  docs/verdict_policy.md                           role table between GENERATED markers
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEF = ROOT / "src/sce_integration/verdict_taxonomy.def"
PY_OUT = ROOT / "tools/verdict_taxonomy_gen.py"
SH_OUT = ROOT / "dut/env/verdict_taxonomy.gen.sh"
RS_OUT = ROOT / "dut/env/orchestrator/src/verdict_taxonomy.gen.rs"
DOC = ROOT / "docs/verdict_policy.md"

DOC_BEGIN = "<!-- GENERATED:role-table BEGIN (gen_verdict_taxonomy.py) -->"
DOC_END = "<!-- GENERATED:role-table END -->"

# The one sentinel class that is never authored in donedata (runtime-only).
SENTINEL = "running"

_CLASS_RE = re.compile(r'TC8_VERDICT_CLASS\(\s*(\w+)\s*,\s*"([^"]+)"\s*,\s*(\d+)\s*\)')
_ROLE_RE = re.compile(r'TC8_VERDICT_ROLE\(\s*"([^"]+)"\s*,\s*(\w+)\s*\)')


def parse():
    raw = DEF.read_text(encoding="utf-8")
    # Strip // line comments — the .def documents the macro syntax in comments,
    # which would otherwise match the macro regexes.
    text = "\n".join(line.split("//", 1)[0] for line in raw.splitlines())
    classes = [(m.group(1), m.group(2), int(m.group(3))) for m in _CLASS_RE.finditer(text)]
    enum_to_name = {e: n for e, n, _ in classes}
    roles = [(m.group(1), enum_to_name[m.group(2)]) for m in _ROLE_RE.finditer(text)]
    if not classes or not roles:
        sys.exit("gen_verdict_taxonomy: parsed 0 classes or roles — bad .def")
    return classes, roles


def render_py(classes, roles) -> str:
    authored = [(n, x) for _, n, x in classes if n != SENTINEL]
    nonconc = [n for n, x in authored if x not in (0, 1)]
    lines = [
        "# GENERATED by tools/gen_verdict_taxonomy.py from",
        "# src/sce_integration/verdict_taxonomy.def — DO NOT EDIT.",
        "# Regenerate: python3 tools/gen_verdict_taxonomy.py",
        "",
        "# role -> verdict class (docs/verdict_policy.md). The class is a pure",
        "# function of the role; the audit enforces donedata class == ROLE_POLICY[role].",
        "ROLE_POLICY = {",
    ]
    width = max(len(r) for r, _ in roles)
    for r, c in roles:
        lines.append(f'    "{r}":{" " * (width - len(r))} "{c}",')
    lines += [
        "}",
        "",
        "# The classes a donedata verdict may carry (the runtime-only",
        f'# "{SENTINEL}" sentinel is excluded — it is never authored).',
        "VALID_CLASSES = {" + ", ".join(f'"{n}"' for n, _ in authored) + "}",
        "",
        "# Process exit code per class.",
        "EXIT_CODES = {" + ", ".join(f'"{n}": {x}' for n, x in authored) + "}",
        "",
        "# Non-conclusion classes (exit not in {0,1}) — the smoke gate auto-skips these.",
        "NONCONCLUSION_CLASSES = {" + ", ".join(f'"{n}"' for n in nonconc) + "}",
        "",
    ]
    return "\n".join(lines)


def render_sh(classes) -> str:
    authored = [(n, x) for _, n, x in classes if n != SENTINEL]
    success = [n for n, x in authored if x == 0]
    nonconc = [n for n, x in authored if x not in (0, 1)]
    return "\n".join([
        "# GENERATED by tools/gen_verdict_taxonomy.py from",
        "# src/sce_integration/verdict_taxonomy.def — DO NOT EDIT.",
        "# Regenerate: python3 tools/gen_verdict_taxonomy.py",
        "#",
        "# Sourced by smoke-test.sh. `skip` is a smoke-runner concept (capability /",
        "# topology) layered onto the non-conclusion disposition, not a DUT verdict.",
        f'TC8_VERDICT_SUCCESS="{success[0]}"',
        f'TC8_VERDICT_NONCONCLUSION_RE="{"|".join(nonconc)}"',
        "",
    ])


def render_rs(classes) -> str:
    authored = [(n, x) for _, n, x in classes if n != SENTINEL]
    success = [n for n, x in authored if x == 0]
    fail = [n for n, x in authored if x == 1]
    nonconc = [n for n, x in authored if x not in (0, 1)]
    # The Rust mirror exposes exactly one success and one fail wire-name. A future
    # .def with two authored exit-0 (or exit-1) classes would make SUCCESS/FAIL
    # ambiguous; fail loud rather than silently picking the first — the taxonomy
    # is meant to be uneditable-without-detection, and so is its generator.
    if len(success) != 1 or len(fail) != 1:
        sys.exit(
            f"gen_verdict_taxonomy: expected exactly 1 success + 1 fail authored "
            f"class, got success={success} fail={fail}"
        )
    nonconc_arr = ", ".join(f'"{n}"' for n in nonconc)
    return "\n".join([
        "// GENERATED by tools/gen_verdict_taxonomy.py from",
        "// src/sce_integration/verdict_taxonomy.def — DO NOT EDIT.",
        "// Regenerate: python3 tools/gen_verdict_taxonomy.py",
        "//",
        "// include!-d as the `taxonomy` module and consumed by dispatch.rs::classify",
        "// so the orchestrator derives the verdict wire-names from the same .def as",
        "// the C++/bash/Python consumers. `skip` is a smoke-runner concept",
        "// (capability / topology) layered on the non-conclusion disposition, not a",
        "// DUT verdict class, so it is not generated here.",
        "",
        "/// Wire-name of the success class (gate-green, exit 0).",
        f'pub const SUCCESS: &str = "{success[0]}";',
        "",
        "/// Wire-name of the gate-red failure class (exit 1).",
        f'pub const FAIL: &str = "{fail[0]}";',
        "",
        "/// Non-conclusion class wire-names (exit code not 0 or 1): routed to",
        "/// a non-gating skip but counted against the non-conclusion ceiling.",
        f"pub const NONCONCLUSION: &[&str] = &[{nonconc_arr}];",
        "",
    ])


def render_doc_table(roles) -> str:
    rows = ["| role | class |", "|------|-------|"]
    for r, c in roles:
        rows.append(f"| `{r}` | `{c}` |")
    return "\n".join(rows)


def splice_doc(roles) -> str:
    text = DOC.read_text(encoding="utf-8")
    table = render_doc_table(roles)
    block = f"{DOC_BEGIN}\n{table}\n{DOC_END}"
    if DOC_BEGIN in text and DOC_END in text:
        pre = text[: text.index(DOC_BEGIN)]
        post = text[text.index(DOC_END) + len(DOC_END):]
        return pre + block + post
    sys.exit(
        f"gen_verdict_taxonomy: markers not found in {DOC.name}; add\n  {DOC_BEGIN}\n  {DOC_END}"
    )


def main() -> int:
    check = "--check" in sys.argv[1:]
    classes, roles = parse()
    outputs = {
        PY_OUT: render_py(classes, roles),
        SH_OUT: render_sh(classes),
        RS_OUT: render_rs(classes),
        DOC: splice_doc(roles),
    }
    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not check:
                path.write_text(content, encoding="utf-8")
    rel = lambda p: p.relative_to(ROOT)
    if check:
        if stale:
            print("STALE generated files (run: python3 tools/gen_verdict_taxonomy.py):")
            for p in stale:
                print(f"  {rel(p)}")
            return 1
        print("verdict taxonomy generated files are up to date")
        return 0
    for p in outputs:
        print(f"wrote {rel(p)}" if p in stale else f"unchanged {rel(p)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
