#!/usr/bin/env python3
"""Generate the Python site mirror of the SOME/IP-SD wire decoder from the
single source src/sce_integration/someip_sd_wire.def.

The .def is #included directly by the C++ authoritative decoder
(src/sce_integration/someip_captured.h), so the C++ side cannot drift from it.
This tool derives the Python decoder used by the documentation-site tooling
(site/scripts/decode_pcap.py) from the same .def, so both languages share one
layout. See docs/tech-debt.md TD-01.

Run with no args to (re)write the generated file; run with --check to verify it
is up to date (CI / pre-commit freshness gate). Both modes also run a built-in
self-test that decodes golden vectors through the freshly rendered decoder and
asserts the field values, so a wrong offset/width in the .def fails loudly
rather than silently producing a consistent-but-wrong mirror in both languages.

Output:
  site/scripts/someip_sd_wire_generated.py   imported by decode_pcap.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEF = ROOT / "src/sce_integration/someip_sd_wire.def"
PY_OUT = ROOT / "site/scripts/someip_sd_wire_generated.py"

# Data rows in the .def. Directive lines (#define/#undef ...) start with '#'
# and are skipped; everything else with a TC8_SD_ prefix must parse or it is a
# fat-fingered SSOT line — fail loud (a dropped row vanishes from the mirror
# while leaving the file green).
_FIELD_RE = re.compile(
    r"^TC8_SD_(HEADER|ENTRIESLEN|OPTION)_FIELD\(\s*(\w+)\s*,\s*(\w+)\s*,"
    r"\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)\s*$")
_ENTRY_FIELD_RE = re.compile(
    r"^TC8_SD_ENTRY_FIELD\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,"
    r"\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)\s*$")
_ENTRY_TYPE_RE = re.compile(r"^TC8_SD_ENTRY_TYPE\(\s*(\w+)\s*,\s*(\w+)\s*\)\s*$")
_OPTION_ADDR_RE = re.compile(r"^TC8_SD_OPTION_ADDR\(\s*(\w+)\s*,\s*(\w+)\s*\)\s*$")
_OPTION_TYPE_RE = re.compile(r"^TC8_SD_OPTION_TYPE\(\s*(\w+)\s*\)\s*$")


class Schema:
    def __init__(self):
        self.header = []        # [(member, off, size, shift, mask)]
        self.entries_len = []   # [(member, off, size, shift, mask)]
        self.entry_common = []  # [(member, off, size, shift, mask)]
        self.entry_tail = {}    # group -> [(member, off, size, shift, mask)]
        self.entry_types = []   # [(type_int, group)]
        self.option = []        # [("field", member, off, size, shift, mask) | ("addr", member, off)]
        self.option_types = []  # [type_int]


def parse() -> Schema:
    s = Schema()
    for raw in DEF.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("//") or line.startswith("#"):
            continue
        if not line.startswith("TC8_SD_"):
            continue
        m = _FIELD_RE.match(line)
        if m is not None:
            kind, member, off, size, shift, mask = m.groups()
            row = (member, int(off, 0), int(size, 0), int(shift, 0), int(mask, 0))
            if kind == "HEADER":
                s.header.append(row)
            elif kind == "ENTRIESLEN":
                s.entries_len.append(row)
            else:  # OPTION
                s.option.append(("field",) + row)
            continue
        m = _ENTRY_FIELD_RE.match(line)
        if m is not None:
            group, member, off, size, shift, mask = m.groups()
            row = (member, int(off, 0), int(size, 0), int(shift, 0), int(mask, 0))
            if group == "common":
                s.entry_common.append(row)
            else:
                s.entry_tail.setdefault(group, []).append(row)
            continue
        m = _ENTRY_TYPE_RE.match(line)
        if m is not None:
            s.entry_types.append((int(m.group(1), 0), m.group(2)))
            continue
        m = _OPTION_ADDR_RE.match(line)
        if m is not None:
            s.option.append(("addr", m.group(1), int(m.group(2), 0)))
            continue
        m = _OPTION_TYPE_RE.match(line)
        if m is not None:
            s.option_types.append(int(m.group(1), 0))
            continue
        sys.exit(f"gen_someip_sd_wire: malformed .def row (TC8_SD_ prefix but "
                 f"unparseable): {raw!r}")
    if not (s.entry_common and s.header and s.option and s.entry_types):
        sys.exit("gen_someip_sd_wire: parsed an incomplete schema — bad .def")
    return s


def _off_expr(base: str, off: int) -> str:
    if base == "0":  # record starts at the buffer origin
        return str(off)
    return base if off == 0 else f"{base} + {off}"


def _read_expr(base: str, off: int, size: int, shift: int, mask: int) -> str:
    return f"_read(buf, {_off_expr(base, off)}, {size}, {shift}, 0x{mask:02x})"


def render_py(s: Schema) -> str:
    lines = [
        "# GENERATED by tools/gen_someip_sd_wire.py from",
        "# src/sce_integration/someip_sd_wire.def — DO NOT EDIT.",
        "# Regenerate: python3 tools/gen_someip_sd_wire.py",
        "#",
        "# Python mirror of the SOME/IP-SD wire decode. The C++ authoritative",
        "# decoder (src/sce_integration/someip_captured.h) #includes the same",
        "# .def directly, so this file and the harness share one layout. Imported",
        "# by site/scripts/decode_pcap.py. See docs/tech-debt.md TD-01.",
        "",
        "",
        "def _read(buf, off, size, shift, mask):",
        '    """Big-endian field read; twin of ::tc8::wire::readBe (C++)."""',
        "    value = 0",
        "    for i in range(size):",
        "        value = (value << 8) | buf[off + i]",
        "    return (value >> shift) & mask",
        "",
        "",
        "def _ipv4(buf, off):",
        '    return ".".join(str(b) for b in buf[off:off + 4])',
        "",
        "",
    ]

    # entry Type -> tail group
    grp_items = ", ".join(f"0x{t:02x}: {g!r}" for t, g in s.entry_types)
    lines.append(f"SD_ENTRY_TAIL_GROUP = {{{grp_items}}}")
    opt_items = ", ".join(f"0x{t:02x}" for t in s.option_types)
    trailing = "," if len(s.option_types) == 1 else ""
    lines.append(f"SD_IPV4_OPTION_TYPES = ({opt_items}{trailing})")
    lines += ["", ""]

    # decode_sd_header(buf) -> {flags, reserved}
    lines.append("def decode_sd_header(buf):")
    lines.append('    """SD header flags + 24-bit reserved (caller guarantees >= 4 bytes)."""')
    lines.append("    return {")
    for member, off, size, shift, mask in s.header:
        lines.append(f'        "{member}": {_read_expr("0", off, size, shift, mask)},')
    lines.append("    }")
    lines += ["", ""]

    # decode_sd_entries_len(buf) -> int
    member, off, size, shift, mask = s.entries_len[0]
    lines.append("def decode_sd_entries_len(buf):")
    lines.append('    """LengthOfEntriesArray (caller guarantees >= 8 bytes)."""')
    lines.append(f"    return {_read_expr('0', off, size, shift, mask)}")
    lines += ["", ""]

    # decode_sd_entry(buf, off, e_type) -> dict
    lines.append("def decode_sd_entry(buf, off, e_type):")
    lines.append('    """16-byte SD entry. Common fields always; the tail group')
    lines.append('    matching e_type only (the C++ struct carries both tails, but a')
    lines.append('    dict need only hold the meaningful one)."""')
    lines.append("    e = {}")
    for member, off_f, size, shift, mask in s.entry_common:
        lines.append(f'    e["{member}"] = {_read_expr("off", off_f, size, shift, mask)}')
    lines.append("    group = SD_ENTRY_TAIL_GROUP.get(e_type)")
    first = True
    for group, rows in s.entry_tail.items():
        kw = "if" if first else "elif"
        first = False
        lines.append(f'    {kw} group == "{group}":')
        for member, off_f, size, shift, mask in rows:
            lines.append(f'        e["{member}"] = {_read_expr("off", off_f, size, shift, mask)}')
    lines.append("    return e")
    lines += ["", ""]

    # decode_sd_option_ipv4(buf, off) -> dict
    lines.append("def decode_sd_option_ipv4(buf, off):")
    lines.append('    """IPv4 endpoint/multicast/sd-endpoint option tail."""')
    lines.append("    return {")
    for row in s.option:
        if row[0] == "addr":
            _, member, off_f = row
            arg = "off" if off_f == 0 else f"off + {off_f}"
            lines.append(f'        "{member}": _ipv4(buf, {arg}),')
        else:
            _, member, off_f, size, shift, mask = row
            lines.append(f'        "{member}": {_read_expr("off", off_f, size, shift, mask)},')
    lines.append("    }")
    lines.append("")
    return "\n".join(lines)


# --- self-test: decode golden vectors through the rendered module -----------
def self_test(module) -> list[str]:
    """Decode hand-checked vectors and assert the field values, so a wrong
    offset/width in the .def is caught here rather than silently mirrored."""
    problems: list[str] = []

    def check(label, got, want):
        if got != want:
            problems.append(f"{label}: got {got!r}, want {want!r}")

    # Subscribe entry (Type 0x06): Reserved(12b)=0, Counter(4b)=5, EG=0x0042.
    sub = bytes.fromhex("06000010" "12340001" "01000003" "00050042")
    e = module.decode_sd_entry(sub, 0, 0x06)
    check("sub.type", e.get("type"), 0x06)
    check("sub.num_opt1", e.get("num_opt1"), 1)
    check("sub.num_opt2", e.get("num_opt2"), 0)
    check("sub.service_id", e.get("service_id"), 0x1234)
    check("sub.instance_id", e.get("instance_id"), 0x0001)
    check("sub.major_version", e.get("major_version"), 0x01)
    check("sub.ttl", e.get("ttl"), 3)
    check("sub.entry_reserved", e.get("entry_reserved"), 0)
    check("sub.counter", e.get("counter"), 5)
    check("sub.eventgroup_id", e.get("eventgroup_id"), 0x0042)
    check("sub.no_minor_version", "minor_version" in e, False)

    # Offer entry (Type 0x01): Minor Version = 0xAABBCCDD, ttl = 0xFFFFFF.
    off = bytes.fromhex("01000010" "12340001" "01ffffff" "aabbccdd")
    e = module.decode_sd_entry(off, 0, 0x01)
    check("off.minor_version", e.get("minor_version"), 0xAABBCCDD)
    check("off.ttl", e.get("ttl"), 0xFFFFFF)
    check("off.no_counter", "counter" in e, False)

    # IPv4 endpoint option: 192.168.1.10, UDP (0x11), port 30490.
    opt = bytes.fromhex("0009" "04" "00" "c0a8010a" "00" "11" "771a")
    o = module.decode_sd_option_ipv4(opt, 0)
    check("opt.reserved1", o.get("reserved1"), 0x00)
    check("opt.ipv4", o.get("ipv4"), "192.168.1.10")
    check("opt.reserved2", o.get("reserved2"), 0x00)
    check("opt.l4_proto", o.get("l4_proto"), 0x11)
    check("opt.port", o.get("port"), 30490)

    # SD header.
    hdr = module.decode_sd_header(bytes.fromhex("c0000000"))
    check("hdr.sd_flags", hdr.get("sd_flags"), 0xC0)
    check("hdr.sd_reserved", hdr.get("sd_reserved"), 0x000000)
    check("entries_len", module.decode_sd_entries_len(bytes.fromhex("00000000" "00000010")), 0x10)
    return problems


def _load_module(source: str):
    import types
    mod = types.ModuleType("someip_sd_wire_generated_probe")
    exec(compile(source, "<generated>", "exec"), mod.__dict__)
    return mod


def main() -> int:
    check = "--check" in sys.argv[1:]
    schema = parse()
    content = render_py(schema)

    # Self-test the freshly rendered decoder regardless of mode.
    problems = self_test(_load_module(content))

    current = PY_OUT.read_text(encoding="utf-8") if PY_OUT.exists() else None
    stale = current != content
    rel = PY_OUT.relative_to(ROOT)

    if check:
        rc = 0
        if stale:
            print(f"STALE generated file (run: python3 tools/gen_someip_sd_wire.py): {rel}")
            rc = 1
        if problems:
            print("someip_sd_wire self-test failed (the .def has a wrong offset/width):")
            for p in problems:
                print(f"  {p}")
            rc = 1
        if rc == 0:
            print(f"{rel} is up to date and self-test passed")
        return rc

    if problems:
        print("someip_sd_wire self-test failed (the .def has a wrong offset/width):")
        for p in problems:
            print(f"  {p}")
        return 1
    if stale:
        PY_OUT.write_text(content, encoding="utf-8")
        print(f"wrote {rel}")
    else:
        print(f"unchanged {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
