#!/usr/bin/env python3
"""Generate the Rust + Bash mirrors of the cross-language wire/fixture constants
from the single source tools/wire.def, and cross-verify the C++ headers that own
the same values against it.

Run with no args to (re)write the generated files; run with --check to verify
they are up to date AND that every `cpp=`-annotated constant still matches its
C++ header (CI / pre-commit freshness + drift gate). The C++ check also runs in
write mode — a value drift is an error regardless of how the tool was invoked.

Outputs:
  dut/env/orchestrator/src/wire.gen.rs   include!-d as the `wire` module
  dut/env/wire.gen.sh                     sourced by smoke-test.sh; profiles read
                                          $TC8_WIRE_<NAME>
"""
from __future__ import annotations

import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEF = ROOT / "tools/wire.def"
RS_OUT = ROOT / "dut/env/orchestrator/src/wire.gen.rs"
SH_OUT = ROOT / "dut/env/wire.gen.sh"

# /// doc line, and the TC8_WIRE_<KIND>(NAME, "value"[, cpp=relpath:sym]) entry.
_DOC_RE = re.compile(r'^\s*///\s?(.*)$')
_ENTRY_RE = re.compile(
    r'^TC8_WIRE_(IPV4|MAC|U16|STR|INT)\(\s*(\w+)\s*,\s*"([^"]*)"'
    r'\s*(?:,\s*cpp=([^)\s]+))?\s*\)\s*$'
)


class Entry:
    __slots__ = ("kind", "name", "value", "cpp", "docs")

    def __init__(self, kind, name, value, cpp, docs):
        self.kind = kind
        self.name = name
        self.value = value
        self.cpp = cpp  # "relpath:symbol" or None
        self.docs = docs  # list[str]


def parse() -> list[Entry]:
    entries: list[Entry] = []
    pending: list[str] = []
    for line in DEF.read_text(encoding="utf-8").splitlines():
        m = _DOC_RE.match(line)
        if m is not None:
            pending.append(m.group(1).rstrip())
            continue
        m = _ENTRY_RE.match(line)
        if m is not None:
            entries.append(Entry(m.group(1), m.group(2), m.group(3),
                                 m.group(4), pending))
            pending = []
            continue
        # A line that INTENDS to be an entry (TC8_WIRE_ prefix) but failed the
        # full regex is a fat-fingered SSOT line — fail loud, never silently drop
        # it (a dropped constant vanishes from both generated files AND the C++
        # cross-check while the `if not entries` guard stays green).
        if line.lstrip().startswith("TC8_WIRE_"):
            sys.exit(f"gen_wire_manifest: malformed entry (TC8_WIRE_ prefix but "
                     f"unparseable): {line!r}")
        # Any other line (blank, '#' comment, separator) breaks doc adjacency.
        pending = []
    if not entries:
        sys.exit("gen_wire_manifest: parsed 0 entries — bad wire.def")
    return entries


def render_rs(entries: list[Entry]) -> str:
    lines = [
        "// GENERATED by tools/gen_wire_manifest.py from",
        "// tools/wire.def — DO NOT EDIT.",
        "// Regenerate: python3 tools/gen_wire_manifest.py",
        "//",
        "// include!-d as the `wire` module (main.rs). Single home for the wire/",
        "// fixture constants shared across the C++ stimulus builders, this crate,",
        "// and the bash smoke-test profiles. Each constant names its external SSOT",
        "// in wire.def, where the `cpp=` ones are cross-checked against the C++",
        "// headers. A drift here silently turns a positive test into a false pass.",
        "",
    ]
    for e in entries:
        for d in e.docs:
            lines.append(("/// " + d).rstrip())
        if e.kind == "INT":
            lines.append(f"pub const {e.name}: u32 = {e.value};")
        else:
            lines.append(f'pub const {e.name}: &str = "{e.value}";')
        lines.append("")
    return "\n".join(lines)


def render_sh(entries: list[Entry]) -> str:
    lines = [
        "# GENERATED by tools/gen_wire_manifest.py from",
        "# tools/wire.def — DO NOT EDIT.",
        "# Regenerate: python3 tools/gen_wire_manifest.py",
        "#",
        "# Sourced by smoke-test.sh; topology profiles read $TC8_WIRE_<NAME>. These",
        "# are the canonical values; consumers apply TC8_TOPOLOGY_* / profile",
        "# overrides on top (e.g. `${TC8_TOPOLOGY_TESTER_IP:-$TC8_WIRE_TESTER_IP}`).",
        "",
    ]
    for e in entries:
        lines.append(f'TC8_WIRE_{e.name}="{e.value}"')
    lines.append("")
    return "\n".join(lines)


# --- C++ cross-check --------------------------------------------------------
def _strip_cpp_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


def _decode_ipv4(rhs: str) -> str:
    """Evaluate a C++ NBO uint32 IPv4 initialiser to dotted-decimal, accepting
    ONLY the two byte-explicit forms in tree and REJECTING anything else — a
    future C++ style change MUST fail --check loudly, not silently mis-decode
    (best-effort regex-scraping was the exact "silent false pass" the manifest
    header warns against). Accepted:
      (a) a lone hex literal `0xAABBCCDDU` (the `*Be` NBO convention), or
      (b) exactly four `static_cast<...>(<decimal 0-255>) << {0,8,16,24}` terms.
    Both store the on-wire byte sequence in little-endian memory order, so the
    dotted form is the LE byte unpack of the evaluated uint32."""
    s = rhs.strip()
    # Form (a): a lone hex literal (optionally U-suffixed), nothing else.
    m = re.fullmatch(r"0[xX]([0-9A-Fa-f]{1,8})[uU]?", s)
    if m is not None:
        value = int(m.group(1), 16)
        return ".".join(str(b) for b in struct.pack("<I", value & 0xFFFFFFFF))
    # Form (b): exactly four static_cast shift terms covering bytes 0/8/16/24.
    terms = re.findall(r"static_cast<[^>]+>\(\s*(\d+)[uU]?\s*\)\s*<<\s*(\d+)", s)
    if len(terms) == 4 and sorted(int(sh) for _, sh in terms) == [0, 8, 16, 24]:
        value = 0
        for num, sh in terms:
            b = int(num)
            if b > 255:
                raise ValueError(f"IPv4 shift operand {b} > 255: {rhs!r}")
            value |= b << int(sh)
        return ".".join(str(byte) for byte in struct.pack("<I", value & 0xFFFFFFFF))
    raise ValueError(
        "unrecognised C++ IPv4 initialiser — decoder accepts only a lone "
        f"0x..U literal or four static_cast<..>(N)<<{{0,8,16,24}} terms: {rhs!r}")


def _decode_mac(body: str) -> str:
    bytes_ = re.findall(r"0[xX]([0-9A-Fa-f]{1,2})", body)
    if len(bytes_) != 6:
        raise ValueError(f"expected 6 MAC bytes, got {len(bytes_)}: {body!r}")
    return ":".join(f"{int(b, 16):02X}" for b in bytes_)


def _decode_u16(rhs: str) -> str:
    m = re.search(r"0[xX][0-9A-Fa-f]+|\d+", rhs)
    if m is None:
        raise ValueError(f"no integer literal in u16 initialiser: {rhs!r}")
    return f"0x{int(m.group(0), 0):04X}"


def _norm(kind: str, value: str) -> str:
    """Canonicalise a wire.def value to the same form the C++ decoder emits, so
    the comparison is representation-insensitive (MAC case, hex width)."""
    if kind == "MAC":
        return ":".join(f"{int(o, 16):02X}" for o in value.split(":"))
    if kind == "U16":
        return f"0x{int(value, 0):04X}"
    return value  # IPV4 dotted compares verbatim


def check_cpp(entries: list[Entry]) -> list[str]:
    problems: list[str] = []
    for e in entries:
        if not e.cpp:
            continue
        relpath, _, sym = e.cpp.partition(":")
        path = ROOT / relpath
        if not path.exists():
            problems.append(f"{e.name}: cpp header {relpath} not found")
            continue
        text = _strip_cpp_comments(path.read_text(encoding="utf-8"))
        try:
            if e.kind == "MAC":
                m = re.search(rf"\b{re.escape(sym)}\b\s*\{{([^}}]*)\}}",
                              text, re.DOTALL)
                if m is None:
                    raise ValueError("symbol/initialiser not found")
                decoded = _decode_mac(m.group(1))
            elif e.kind in ("IPV4", "U16"):
                m = re.search(rf"\b{re.escape(sym)}\b\s*=\s*(.*?);",
                              text, re.DOTALL)
                if m is None:
                    raise ValueError("symbol/initialiser not found")
                decoded = (_decode_ipv4 if e.kind == "IPV4" else _decode_u16)(m.group(1))
            else:
                problems.append(f"{e.name}: cpp= on unsupported kind {e.kind}")
                continue
        except ValueError as exc:
            problems.append(f"{e.name}: parsing {relpath}:{sym} failed — {exc}")
            continue
        expected = _norm(e.kind, e.value)
        if decoded != expected:
            problems.append(
                f"{e.name}: wire.def has {expected} but {relpath}:{sym} "
                f"decodes to {decoded} — edit them together")
    return problems


def main() -> int:
    check = "--check" in sys.argv[1:]
    entries = parse()
    outputs = {RS_OUT: render_rs(entries), SH_OUT: render_sh(entries)}
    rel = lambda p: p.relative_to(ROOT)

    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not check:
                path.write_text(content, encoding="utf-8")

    cpp_problems = check_cpp(entries)

    if check:
        rc = 0
        if stale:
            print("STALE generated files (run: python3 tools/gen_wire_manifest.py):")
            for p in stale:
                print(f"  {rel(p)}")
            rc = 1
        if cpp_problems:
            print("C++ wire-constant drift (wire.def disagrees with the headers):")
            for msg in cpp_problems:
                print(f"  {msg}")
            rc = 1
        if rc == 0:
            print("wire manifest generated files are up to date and match C++")
        return rc

    for p in outputs:
        print(f"wrote {rel(p)}" if p in stale else f"unchanged {rel(p)}")
    if cpp_problems:
        print("C++ wire-constant drift (wire.def disagrees with the headers):")
        for msg in cpp_problems:
            print(f"  {msg}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
