#!/usr/bin/env python3
"""Generate the Python site mirror of the DHCPv4 BOOTP fixed-header decoder
from the single source src/sce_integration/dhcpv4_wire.def.

The .def is #included directly by the C++ authoritative decoder
(src/sce_integration/dhcpv4_wire.h, called from src/dissect/packet_pipeline.cpp),
so the C++ side cannot drift from it. This tool derives the Python decoder used
by the documentation-site tooling (site/scripts/decode_pcap.py) from the same
.def, so both languages share one layout. See docs/tech-debt.md TD-02.

Run with no args to (re)write the generated file; run with --check to verify it
is up to date (CI / pre-commit freshness gate). Both modes also run a built-in
self-test that decodes a golden vector through the freshly rendered decoder and
asserts the field values, so a wrong offset/width in the .def fails loudly
rather than silently producing a consistent-but-wrong mirror in both languages.

Output:
  site/scripts/dhcpv4_wire_generated.py   imported by decode_pcap.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEF = ROOT / "src/sce_integration/dhcpv4_wire.def"
PY_OUT = ROOT / "site/scripts/dhcpv4_wire_generated.py"

# Data rows in the .def. Directive lines (#define/#undef ...) start with '#'
# and are skipped; trailing // comments are stripped before matching so rows
# may be documented inline. Anything left with a TC8_DHCP_ prefix must parse
# or it is a fat-fingered SSOT line — fail loud (a dropped row vanishes from
# the mirror while leaving the file green).
_FIELD_RE = re.compile(r"^TC8_DHCP_FIELD\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)$")
_ADDR_RE = re.compile(r"^TC8_DHCP_ADDR\(\s*(\w+)\s*,\s*(\w+)\s*\)$")
_BYTES_RE = re.compile(r"^TC8_DHCP_BYTES\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)$")
_CONST_RE = re.compile(r"^TC8_DHCP_CONST\(\s*(\w+)\s*,\s*(\w+)\s*\)$")


class Schema:
    def __init__(self):
        self.fields = []   # [("field"|"addr"|"bytes", member, off[, size|len])]
        self.consts = []   # [(name, raw_value_token, int_value)]


def parse() -> Schema:
    s = Schema()
    for raw in DEF.read_text(encoding="utf-8").splitlines():
        line = raw.split("//", 1)[0].strip()
        if not line or line.startswith("#"):
            continue
        if not line.startswith("TC8_DHCP_"):
            continue
        m = _FIELD_RE.match(line)
        if m is not None:
            member, off, size = m.groups()
            s.fields.append(("field", member, int(off, 0), int(size, 0)))
            continue
        m = _ADDR_RE.match(line)
        if m is not None:
            member, off = m.groups()
            s.fields.append(("addr", member, int(off, 0)))
            continue
        m = _BYTES_RE.match(line)
        if m is not None:
            member, off, length = m.groups()
            s.fields.append(("bytes", member, int(off, 0), int(length, 0)))
            continue
        m = _CONST_RE.match(line)
        if m is not None:
            name, value = m.groups()
            s.consts.append((name, value, int(value, 0)))
            continue
        sys.exit(f"gen_dhcpv4_wire: malformed .def row (TC8_DHCP_ prefix but "
                 f"unparseable): {raw!r}")
    if not (s.fields and s.consts):
        sys.exit("gen_dhcpv4_wire: parsed an incomplete schema — bad .def")
    return s


def render_py(s: Schema) -> str:
    lines = [
        "# GENERATED by tools/gen_dhcpv4_wire.py from",
        "# src/sce_integration/dhcpv4_wire.def — DO NOT EDIT.",
        "# Regenerate: python3 tools/gen_dhcpv4_wire.py",
        "#",
        "# Python mirror of the DHCPv4 BOOTP fixed-header decode. The C++",
        "# authoritative decoder (src/sce_integration/dhcpv4_wire.h) #includes",
        "# the same .def directly, so this file and the harness share one",
        "# layout. Imported by site/scripts/decode_pcap.py. The options TLV",
        "# chain has no fixed offsets and is walked by the caller, outside this",
        "# mirror. See docs/tech-debt.md TD-02.",
        "",
        "",
        "def _read(buf, off, size):",
        '    """Big-endian field read; twin of ::tc8::wire::readBe (C++)."""',
        "    value = 0",
        "    for i in range(size):",
        "        value = (value << 8) | buf[off + i]",
        "    return value",
        "",
        "",
        "def _ipv4(buf, off):",
        '    return ".".join(str(b) for b in buf[off:off + 4])',
        "",
        "",
    ]

    for name, raw, _ in s.consts:
        lines.append(f"{name} = {raw}")
    lines += ["", ""]

    lines.append("def decode_bootp_fixed_header(buf):")
    lines.append('    """RFC 951 / RFC 2131 BOOTP fixed header (op..chaddr).')
    lines.append('    Caller guarantees at least kOptionsOff bytes."""')
    lines.append("    return {")
    for row in s.fields:
        if row[0] == "field":
            _, member, off, size = row
            lines.append(f'        "{member}": _read(buf, {off}, {size}),')
        elif row[0] == "addr":
            _, member, off = row
            lines.append(f'        "{member}": _ipv4(buf, {off}),')
        else:  # bytes
            _, member, off, length = row
            lines.append(f'        "{member}": bytes(buf[{off}:{off} + {length}]),')
    lines.append("    }")
    lines += ["", ""]

    lines.append("def magic_cookie_valid(buf):")
    lines.append('    """True iff the 4 bytes at kMagicCookieOff equal the cookie."""')
    lines.append("    return _read(buf, kMagicCookieOff, 4) == kMagicCookie")
    lines.append("")
    return "\n".join(lines)


# --- self-test: decode a golden vector through the rendered module ----------
def self_test(module) -> list[str]:
    """Decode a hand-checked BOOTP vector and assert the field values, so a
    wrong offset/width in the .def is caught here rather than silently
    mirrored."""
    problems: list[str] = []

    def check(label, got, want):
        if got != want:
            problems.append(f"{label}: got {got!r}, want {want!r}")

    # DHCPDISCOVER-shaped BOOTP fixed header (240 B) + option 53 = 1 + END.
    buf = bytearray(244)
    buf[0] = 1     # op = BOOTREQUEST
    buf[1] = 1     # htype = Ethernet
    buf[2] = 6     # hlen
    buf[3] = 0     # hops
    buf[4:8] = (0x12345678).to_bytes(4, "big")    # xid
    buf[8:10] = (0).to_bytes(2, "big")            # secs
    buf[10:12] = (0x8000).to_bytes(2, "big")      # flags = BROADCAST
    buf[16:20] = bytes((172, 16, 0, 5))           # yiaddr
    buf[28:34] = bytes.fromhex("aabbccddeeff")    # chaddr MAC
    buf[236:240] = b"\x63\x82\x53\x63"            # magic cookie
    buf[240:244] = bytes((53, 1, 1, 255))         # opt 53 = DISCOVER, END

    f = module.decode_bootp_fixed_header(buf)
    check("op", f.get("op"), 1)
    check("htype", f.get("htype"), 1)
    check("hlen", f.get("hlen"), 6)
    check("hops", f.get("hops"), 0)
    check("xid", f.get("xid"), 0x12345678)
    check("secs", f.get("secs"), 0)
    check("flags", f.get("flags"), 0x8000)
    check("ciaddr", f.get("ciaddr"), "0.0.0.0")
    check("yiaddr", f.get("yiaddr"), "172.16.0.5")
    check("chaddr_mac", bytes(f.get("chaddr", b"")[:6]), bytes.fromhex("aabbccddeeff"))
    check("cookie_ok", module.magic_cookie_valid(buf), True)

    bad = bytearray(buf)
    bad[236] = 0x00
    check("cookie_bad", module.magic_cookie_valid(bad), False)
    return problems


def _load_module(source: str):
    import types
    mod = types.ModuleType("dhcpv4_wire_generated_probe")
    exec(compile(source, "<generated>", "exec"), mod.__dict__)
    return mod


def main() -> int:
    check = "--check" in sys.argv[1:]
    schema = parse()
    content = render_py(schema)

    # Self-test the freshly rendered decoder regardless of mode.
    problems = self_test(_load_module(content))

    current = PY_OUT.read_text(encoding="utf-8") if PY_OUT.exists() else None
    stale = current != content
    rel = PY_OUT.relative_to(ROOT)

    if check:
        rc = 0
        if stale:
            print(f"STALE generated file (run: python3 tools/gen_dhcpv4_wire.py): {rel}")
            rc = 1
        if problems:
            print("dhcpv4_wire self-test failed (the .def has a wrong offset/width):")
            for p in problems:
                print(f"  {p}")
            rc = 1
        if rc == 0:
            print(f"{rel} is up to date and self-test passed")
        return rc

    if problems:
        print("dhcpv4_wire self-test failed (the .def has a wrong offset/width):")
        for p in problems:
            print(f"  {p}")
        return 1
    if stale:
        PY_OUT.write_text(content, encoding="utf-8")
        print(f"wrote {rel}")
    else:
        print(f"unchanged {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
