# GENERATED by tools/gen_verdict_taxonomy.py from
# src/sce_integration/verdict_taxonomy.def — DO NOT EDIT.
# Regenerate: python3 tools/gen_verdict_taxonomy.py

# role -> verdict class (docs/verdict_policy.md). The class is a pure
# function of the role; the audit enforces donedata class == ROLE_POLICY[role].
ROLE_POLICY = {
    "conformant":          "pass",
    "conformant_absence":  "pass",
    "observed_violation":  "fail",
    "precondition_unmet":  "inconclusive",
    "property_unobserved": "inconclusive",
    "test_system_fault":   "error",
}

# The classes a donedata verdict may carry (the runtime-only
# "running" sentinel is excluded — it is never authored).
VALID_CLASSES = {"pass", "fail", "inconclusive", "error"}

# Process exit code per class.
EXIT_CODES = {"pass": 0, "fail": 1, "inconclusive": 2, "error": 3}

# Non-conclusion classes (exit not in {0,1}) — the smoke gate auto-skips these.
NONCONCLUSION_CLASSES = {"inconclusive", "error"}
