#!/usr/bin/env python3
"""Shared scaffolding for the *_wire.py site-mirror generators (TD-01 / TD-02).

Each generator owns only its schema `parse()` and its `render(schema)` body;
this module supplies the parts that must be IDENTICAL across every generated
mirror, so they are written once:
  * the GENERATED-by banner format,
  * the `_read` / `_ipv4` prelude — ONE definition emitted into every mirror, so
    the big-endian read is the literal twin of ::tc8::wire::readBe at every site
    (a consumer applies any `>> shift & mask` slice itself, as the C++ side does),
  * the module loader used by the golden self-test,
  * the --check / regenerate driver (stale detection + self-test + messages).

See docs/tech-debt.md TD-01 (SOME/IP-SD) and TD-02 (DHCPv4 BOOTP).
"""
from __future__ import annotations

import types
from pathlib import Path
from typing import Callable

# Emitted verbatim into every mirror. `_read` is the arithmetic twin of
# ::tc8::wire::readBe (read `size` big-endian bytes); `_ipv4` renders a 4-byte
# address dotted-decimal.
PRELUDE = '''\
def _read(buf, off, size):
    """Big-endian field read; twin of ::tc8::wire::readBe (C++)."""
    value = 0
    for i in range(size):
        value = (value << 8) | buf[off + i]
    return value


def _ipv4(buf, off):
    return ".".join(str(b) for b in buf[off:off + 4])
'''


def banner(generator_rel: str, def_rel: str, body_desc: list[str]) -> str:
    """The `# GENERATED ... DO NOT EDIT` header block, consistent across mirrors."""
    lines = [
        f"# GENERATED by {generator_rel} from",
        f"# {def_rel} — DO NOT EDIT.",
        f"# Regenerate: python3 {generator_rel}",
        "#",
    ]
    lines += [f"# {line}" for line in body_desc]
    return "\n".join(lines)


def load_module(source: str):
    """Compile rendered source into a throwaway module for the self-test."""
    mod = types.ModuleType("wire_mirror_probe")
    exec(compile(source, "<generated>", "exec"), mod.__dict__)
    return mod


def run(tool_name: str, root: Path, py_out: Path,
        render: Callable[[], str], self_test: Callable[[object], list[str]],
        argv: list[str]) -> int:
    """Render, self-test, then either --check (freshness gate) or (re)write.

    The self-test decodes golden vectors through the freshly rendered module so a
    wrong offset/width in the .def fails loudly rather than mirroring silently.
    """
    check = "--check" in argv[1:]
    content = render()
    problems = self_test(load_module(content))
    current = py_out.read_text(encoding="utf-8") if py_out.exists() else None
    stale = current != content
    rel = py_out.relative_to(root)

    def _report_problems() -> None:
        print(f"{tool_name} self-test failed (the .def has a wrong offset/width):")
        for p in problems:
            print(f"  {p}")

    if check:
        rc = 0
        if stale:
            print(f"STALE generated file (run: python3 {tool_name}): {rel}")
            rc = 1
        if problems:
            _report_problems()
            rc = 1
        if rc == 0:
            print(f"{rel} is up to date and self-test passed")
        return rc

    if problems:
        _report_problems()
        return 1
    if stale:
        py_out.write_text(content, encoding="utf-8")
        print(f"wrote {rel}")
    else:
        print(f"unchanged {rel}")
    return 0
