# Verifies the tc8-utm export is consumable out-of-tree: installs the utm-sdk
# component to a temp prefix, then configures, builds AND RUNS
# examples/oem-utm-consumer against it via find_package(tc8-utm). Driven as a
# CTest (see CMakeLists.txt utm_export_smoke) so the exported SDK surface is
# exercised on every run — an unverified export silently rots when a header drops
# off the install list.
#
# Running the consumer, not just building it, is what makes this a gate on the
# SDK's behaviour rather than its link closure. The consumer hosts an OEM module
# and drives it through the exported client: a build-only check proves the archives
# and headers ship, but cannot distinguish an export a tester can actually drive
# from one that merely compiles. The client was never on the install list before
# this change — the export was scoped endpoint-only by design — so this is a
# deliberate widening of the SDK's surface, not the repair of a regression.
#
# Invoked with `cmake -P`; the driver passes TC8_BUILD_DIR / TC8_SOURCE_DIR /
# TC8_CMAKE / TC8_GENERATOR via -D.

set(_root "${TC8_BUILD_DIR}/utm-export-check")
set(_prefix "${_root}/sdk")
set(_consumer "${_root}/consumer")
file(REMOVE_RECURSE "${_root}")

execute_process(
    COMMAND "${TC8_CMAKE}" --install "${TC8_BUILD_DIR}"
            --component utm-sdk --prefix "${_prefix}"
    RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "utm export: install of the utm-sdk component failed (${_rc})")
endif()

set(_gen "")
if(TC8_GENERATOR)
    set(_gen -G "${TC8_GENERATOR}")
endif()
execute_process(
    COMMAND "${TC8_CMAKE}" ${_gen}
            -S "${TC8_SOURCE_DIR}/examples/oem-utm-consumer" -B "${_consumer}"
            "-DCMAKE_PREFIX_PATH=${_prefix}"
    RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "utm export: consumer find_package/configure failed (${_rc})")
endif()

execute_process(
    COMMAND "${TC8_CMAKE}" --build "${_consumer}"
    RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "utm export: consumer link/build failed (${_rc})")
endif()

# Run it: the consumer binds its endpoint and drives its own OEM module through
# the exported client, returning non-zero if the round trip does not produce the
# module's answer. Needs no privileges and no fixture. Note the endpoint binds
# INADDR_ANY — ProtocolServer::start() takes a port and no bind address, so the
# listener is reachable on every interface for the ~millisecond the gate runs;
# only the CLIENT targets loopback. TIMEOUT bounds the run: the client's own
# recv timeouts are bounded, but stop() joins the reactor thread, which a wedged
# poll would block forever.
# PATH_SUFFIXES covers a multi-config generator (Ninja Multi-Config, Visual
# Studio), which drops the executable in a per-config subdirectory — TC8_GENERATOR
# is inherited from the parent build, so that is reachable from here.
find_program(_consumer_exe oem-utm-consumer
    PATHS "${_consumer}"
    PATH_SUFFIXES "" Debug Release RelWithDebInfo MinSizeRel
    NO_DEFAULT_PATH)
if(NOT _consumer_exe)
    message(FATAL_ERROR
        "utm export: consumer built but its executable was not found under ${_consumer}")
endif()
execute_process(COMMAND "${_consumer_exe}" TIMEOUT 60 RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR
        "utm export: consumer could not drive its OEM module over the wire (${_rc})")
endif()

# ── The SDK's runnable tool must ship in bin/ and run ──
# testability-send is the only CLI that addresses an arbitrary (GID, PID), so an
# SDK-only consumer needs it to drive the standard groups its DUT serves; it is
# gated behind TC8_BUILD_HARNESS in the harness executable, so the SDK installs it
# as its own tc8-testability-send. Verify the install shipped it AND that it runs:
# --help exits 0 only if the standalone executable linked and starts, catching
# both a dropped install and a broken standalone link that the header/library
# manifest check below cannot see.
find_program(_send_exe tc8-testability-send
    PATHS "${_prefix}/bin"
    NO_DEFAULT_PATH)
if(NOT _send_exe)
    message(FATAL_ERROR
        "utm export: the SDK did not install tc8-testability-send into bin/ — an "
        "SDK-only build would have the client library but no runnable tool to "
        "address the standard service groups")
endif()
execute_process(COMMAND "${_send_exe}" --help
    TIMEOUT 30 RESULT_VARIABLE _rc OUTPUT_QUIET ERROR_QUIET)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR
        "utm export: installed tc8-testability-send did not run cleanly (${_rc})")
endif()

# ── The package manifest must not drift behind the export ──
# tc8-utm-targets.cmake is generated by install(EXPORT): it IS the set of targets
# this package defines. tc8-utm-config.cmake documents that set in prose for the
# consumer who opens it to see what they got. Prose cannot enforce itself, so diff
# the two: every exported tc8:: target must be named in the config. Without this,
# shipping a target and forgetting to document it is silent — and a target a
# consumer never learns about is one they hand-roll instead, which is the failure
# the client's export exists to end.
# Located by glob rather than a hardcoded lib/: CMAKE_INSTALL_LIBDIR resolves to
# lib or lib64 per distro and is not computed in `cmake -P` script mode.
file(GLOB_RECURSE _targets_file "${_prefix}/*/cmake/tc8-utm/tc8-utm-targets.cmake")
file(GLOB_RECURSE _config_file "${_prefix}/*/cmake/tc8-utm/tc8-utm-config.cmake")
if(NOT _targets_file OR NOT _config_file)
    message(FATAL_ERROR
        "utm export: the installed package's cmake files were not found under ${_prefix}")
endif()
file(READ "${_targets_file}" _targets_txt)
file(READ "${_config_file}" _config_txt)
# add_library(tc8::NAME STATIC IMPORTED) / (tc8::NAME INTERFACE IMPORTED)
string(REGEX MATCHALL "add_library\\(tc8::[A-Za-z0-9_]+" _decls "${_targets_txt}")
set(_undocumented "")
foreach(_decl ${_decls})
    string(REGEX REPLACE "^add_library\\(" "" _t "${_decl}")
    string(FIND "${_config_txt}" "${_t}" _found)
    if(_found EQUAL -1)
        list(APPEND _undocumented "${_t}")
    endif()
endforeach()
if(_undocumented)
    string(REPLACE ";" "\n  " _undoc_pretty "${_undocumented}")
    message(FATAL_ERROR
        "utm export: exported target(s) absent from the package manifest "
        "(cmake/tc8-utm-config.cmake.in) — a consumer reading the config would "
        "never learn these exist:\n  ${_undoc_pretty}")
endif()
list(LENGTH _decls _n_targets)

message(STATUS
    "utm export: find_package(tc8-utm) consumer configured, built + wire-driven OK; "
    "${_n_targets} exported target(s), all documented in the package manifest")
